version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: koprulu_db
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
